title: Website

tabs:
  Dashboard:
    label: Seiten
    icon: page
    columns:
      - width: 2/3
        sections:
          pages:
            type: pages
            headline: Seiten
      - width: 1/3
        sections:
          dates: sections/dates
  settings:
    label: Einstellungen
    icon: cog
    sections:
      fields:
        type: fields
        fields:
          hlcontact:
            label: Kontakt
            type: headline
          phone:
            label: Telefonnummer
            type: link
          address:
            label: Adresse
            type: text
          footernav:
            label: Navigation
            type: pages
          other:
            label: Test field
            type: example-field